### ISSUE TITLE
zwiftmemorymonitor broke - zwift updated to 1.43.3

### ISSUE THREAD

**Issue by danbro-ok** [zwfthcks/zwift-memory-monitor#55]
you had mentioned last time to open issue instead of posting to fb zwift coders.

**Comment by jeroni7100** [comment]
Provided you make sure that Zwift isn't elevated it should work. I used it with 1.43.3 yesterday and with 1.44 right now.

**Comment by jeroni7100** [comment]
Please provide a bit more information if it doesn't work (terminal output from a failing example and also a memory dump of zwiftapp.exe if possible).

**Comment by danbro-ok** [comment]
you are right.  I think it was elevated.  Today it worked without change.  my bad.  apologies.
