### ISSUE TITLE
World offset is wrong for 1.49.0

### ISSUE THREAD

**Issue by stigpo** [zwfthcks/zwift-memory-monitor#60]
I was trying to make a pull-request with a fix for world lookup in 1.49.0, but I don't seem to have permissions.

Anyway, I think the offset should be 
                world: [6 * 0x28 + 0x18, 'uint32'],
 
(at least it produced the correct world ID for Watopia, Makuri and New York...

**Comment by jeroni7100** [comment]
Fixed by #61
