### ISSUE TITLE
Pattern match not working with Zwift 1.56

### ISSUE THREAD

**Issue by stigpo** [zwfthcks/zwift-memory-monitor#65]
No time to investigate new offsets yet, but it seems like the current patterns does not match in 1.56 (most of the time 2/3). I got a one match, but that produced wrong numbers, so they clearly shifted stuff around more than usual.

**Comment by jeroni7100** [comment]
Should be fixed in 2.1.9 (I think)

**Comment by jeroni7100** [comment]
Not working correctly. Reopening.

**Comment by jeroni7100** [comment]
Closing again - did work anyway
